# Generated by Django 3.0.8 on 2020-07-13 23:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Introduce el titulo', max_length=35)),
                ('contenido', models.TextField(help_text='Escribe el contenido de la Noticia')),
            ],
            managers=[
                ('blogs', django.db.models.manager.Manager()),
            ],
        ),
    ]
